pipeline {
  agent {
    docker { image 'openjdk:11' }
  }

  stages {
    stage('Build') {
      steps {
        git branch: 'main', url: 'https://github.com/GuilhermeAbacherli/inf300.git'
        sh 'cd inf335/trabalho5/2-jenkins-docker; docker build --tag trabalho5_2-jenkins-docker .'
      }
    }
  }
}
