pipeline {
  agent {
    docker { image 'openjdk:11' }
  }

  tools {
    dockerTool 'docker'
  }

  stages {
    stage('Build') {
      steps {
        git branch: 'main', url: 'https://github.com/GuilhermeAbacherli/inf300.git'
        sh 'cd inf335/trabalho5/2-jenkins-docker'
        dockerTool 'build --tag trabalho5_2-jenkins-docker .'
      }
    }

    stage('Run') {
      steps {
        dockerTool 'run --rm trabalho5_2-jenkins-docker'
      }
    }
  }
}
