pipeline {
  agent {
    docker { image 'openjdk:11' }
  }

  stages {
    stage('Init') {
      def dockerHome = tool 'docker'
      env.PATH = "${dockerHome}/bin:${env.PATH}"
    }

    stage('Build') {
      steps {
        git branch: 'main', url: 'https://github.com/GuilhermeAbacherli/inf300.git'
        sh 'cd inf335/trabalho5/2-jenkins-docker; docker build --tag trabalho5_2-jenkins-docker .'
      }
    }

    stage('Run') {
      steps {
        sh 'docker run --rm trabalho5_2-jenkins-docker'
      }
    }
  }
}
